### ISSUE TITLE
Updating order status on using BSE Star APIs

### ISSUE THREAD

**Issue by swetajain** [utkarshohm/mutual-fund-platform#1]
Hi,

We were trying to build a MF transaction platform using BSE star MF APIs. I wanted to know how did you update the transaction status for all orders?

Did you download any batch file and update it or how did you do it?

**Comment by utkarshohm** [comment]
I wrote a scraper that periodically checked order status on BSE star MF platform and updated the status. It was a hacky solution but it was the most automation I could get
