### ISSUE TITLE
Need help in setting up this on a Django project.

### ISSUE THREAD

**Issue by ratnakar24** [utkarshohm/mutual-fund-platform#4]
Hi, Could you please help me in setting up your code on Django project?

**Comment by ankit167** [comment]
I was able to set it up following this guide- https://docs.djangoproject.com/en/2.1/intro/tutorial01/
Just wrap this code in a django based project.

**Comment by hmharshit** [comment]
Hey @ankit167 
Can you share the wrapper which you used to wrap this code? I tried to integrate this but lately getting errors during setup.
Thanks
